### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThomasDev16** [Qbox-project/qbx_policejob#18]
### Summary

Error on handcuffing other players

### Reproduction

1. Use the handcuff item/or event close to a person trying to cuff them

### Expected behavior

I exepected it to work kekw

### Actual behavior

Giving me an error:
![image](https://github.com/Qbox-project/qbx-policejob/assets/87180658/4247faea-cd14-4127-8e01-b8ac8affeec7)

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by buddizer** [comment]
Could you try this again? Tested and unable to repro with latest build.

**Comment by MafewTM** [comment]
Closing after no response in months.
