### ISSUE TITLE
add a /admincar

### ISSUE THREAD

**Issue by pengusource** [Qbox-project/qbx_policejob#35]
### The problem

it would be nice if you could do /admincar so if your an admin you can automatically buy the car your in. 

### Ideal solution

so admins don't always have to go to the pdm to test garages or just developing cars in general. Or if someone buys personal cars you can admin car it and then give it to them. 

### Alternative solutions

None.

### Additional context

No command for /admincar

**Comment by TonybynMp4** [comment]
why was this issue made in policejob lol
