### ISSUE TITLE
police job bug 

### ISSUE THREAD

**Issue by zakleedell1996** [Qbox-project/qbx_policejob#72]
### Summary

cant sent players to jail 

### Reproduction

nothing

### Expected behavior

to work like it should

### Actual behavior

not worked 

### Additional context

![image](https://github.com/Qbox-project/qbx_policejob/assets/107224926/f5af9669-0006-4c80-8cb1-f21730cf283a)

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by MafewTM** [comment]
The error you provided has nothing to do with the jailing of players. Perhaps you included the wrong error?

**Comment by zakleedell1996** [comment]
I reported 2 bugs 1 was the players not going to jail when sent and other
was
What I recently did On Fri, 8 Dec 2023 at 17:53, Matthew <

**Comment by MafewTM** [comment]
Unable to reproduce
