### ISSUE TITLE
qbx_policejob

### ISSUE THREAD

**Issue by Bam-Bum** [Qbox-project/qbx_policejob#79]
### Summary

qbx_policejob does not work with the radial

### Reproduction

1

### Expected behavior

1

### Actual behavior

1

### Additional context

1

### Last Updated

1

### Custom Resources

1

### Resource Rename

1

**Comment by jnccloud** [comment]
this issue should be closed, there's no helpful information. my radial menu works fine.

**Comment by ArturMichalak** [comment]
Closing due to lack of information. Feel free to re-open.
